---
- name: Git install Debian
  apt:
    name: git
    state: present
  ignore_errors: yes
- name: Check git
  shell: git --version
  register: out
- set_fact:
    value: "{{ sudo_var if ( out.rc == 0) else nosudo_var }}"
- name: Print Permissions
  debug:
    msg: "{{ value }}"
- name: Remove git on Debian if it installed
  apt:
    name: git
    state: present
  ignore_errors: yes
